import { useEffect, useMemo, useState } from "react";
import { Download, Eye, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { computeTotals, type Invoice, type InvoiceItem as Item } from "@/lib/invoice";
import {
  advanceInvoiceCounter,
  applyCompanyProfile,
  bankingDetailsOf,
  currentInvoiceNumber,
  defaultCompanyProfile,
  formatPrefsOf,
  hasInvoiceNumbering,
  invoiceNumberingChanged,
  isSchemeGeneratedNumber,
  loadCompanyProfile,
  saveCompanyProfile,
  type CompanyProfile,
} from "@/lib/company-profile";
import { formatDate, formatMoney } from "@/lib/locale-format";
import { CompanyProfileDialog } from "@/components/company-profile-dialog";
import { CurrencySettingsDialog } from "@/components/currency-settings-dialog";
import { InvoicePreviewDialog } from "@/components/invoice-preview-dialog";
import {
  DEFAULT_TEMPLATE_ID,
  getInvoiceTemplate,
  invoiceTemplateList,
  type InvoiceTemplateProps,
} from "@/templates";

const iso = (d: Date) => d.toISOString().slice(0, 10);
const today = new Date();
const due = new Date(today);
due.setDate(today.getDate() + 14);

const initial: Invoice = {
  business: "",
  address: "",
  to: "",
  toPhone: "",
  shipTo: "",
  invoiceNo: "1",
  invoiceNoAutoGenerated: true,
  invoiceNoCounterAdvanced: false,
  date: iso(today),
  dueDate: iso(due),
  items: [{ id: 1, name: "", qty: 1, rate: 0 }],
  taxPercent: 0,
  discount: 0,
  amountPaid: 0,
  notes: "",
  currency: "USD",
  selectedTemplate: DEFAULT_TEMPLATE_ID,
};

export function InvoiceEditor() {
  const [inv, setInv] = useState<Invoice>(initial);
  const [downloading, setDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  // The read-only preview lives in a modal over the editing view — opening or
  // closing it never touches invoice state, so there is no "stuck in preview"
  // mode to manage.
  const [previewOpen, setPreviewOpen] = useState(false);
  // The persisted business identity. Lives under its own localStorage key,
  // is never touched by "Clear invoice", and only the overlay writes it.
  const [profile, setProfile] = useState<CompanyProfile>(defaultCompanyProfile);
  // Has a Company Profile ever been persisted? Auto-numbering only becomes
  // "active" (mount generation, download advancing the counter) once it has —
  // the out-of-the-box defaults drive the dialog preview but don't start
  // consuming numbers on their own.
  const [profileSaved, setProfileSaved] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  // The top summary bar's "Change" link opens this focused dialog — just the
  // currency / date / number formatting, writing back to the same profile.
  const [currencyOpen, setCurrencyOpen] = useState(false);

  useEffect(() => {
    // A first-time visitor (no saved profile) starts from `defaultCompanyProfile`
    // so the numbering section is pre-filled, but nothing is persisted or
    // consumed until they save a profile or clear the invoice.
    const savedProfile = loadCompanyProfile();
    const activeProfile = savedProfile ?? defaultCompanyProfile;

    // Start from the last saved invoice (if any)…
    let base: Invoice = { ...initial };
    const stored = localStorage.getItem("rapidai-invoice");
    let hadStoredInvoice = false;
    if (stored) {
      try {
        const parsed = JSON.parse(stored) as Partial<Invoice>;
        base = { ...base, ...parsed };
        hadStoredInvoice = true;
        // Drop fields removed from the model so they don't linger in storage:
        // `terms` (Payment terms, removed) and the old inline "Bill from" text.
        delete (base as Record<string, unknown>)["terms"];
        delete base.from;
        // Migrate invoices persisted before the numbering flags existed: infer
        // whether the number is still scheme-generated, and assume the old flow
        // (which advanced the counter at generation) already consumed its slot.
        if (typeof parsed.invoiceNoAutoGenerated !== "boolean") {
          base.invoiceNoAutoGenerated = isSchemeGeneratedNumber(base.invoiceNo, activeProfile);
          base.invoiceNoCounterAdvanced = true;
        }
      } catch {
        /* ignore corrupt data */
      }
    }
    // …then let the saved Company Profile fill any field still left blank.
    if (savedProfile) base = applyCompanyProfile(base, savedProfile);

    // A genuinely fresh start (no invoice in storage) shows the profile's
    // current number. The counter is NOT advanced here — it advances only when
    // this invoice is finalised (downloaded) or replaced ("Clear invoice").
    // Gated on a *saved* profile so the out-of-the-box defaults don't activate
    // numbering on their own.
    if (!hadStoredInvoice && savedProfile && hasInvoiceNumbering(activeProfile)) {
      base = {
        ...base,
        invoiceNo: currentInvoiceNumber(activeProfile),
        invoiceNoAutoGenerated: true,
        invoiceNoCounterAdvanced: false,
      };
    }

    if (savedProfile) setProfileSaved(true);
    setProfile(activeProfile);
    setInv(base);
  }, []);
  useEffect(() => {
    const timer = window.setTimeout(
      () => localStorage.setItem("rapidai-invoice", JSON.stringify(inv)),
      400,
    );
    return () => window.clearTimeout(timer);
  }, [inv]);

  // ---- Editing layer: state + patch functions + calculations ----
  // This is template-agnostic. Templates never touch it; they receive the
  // invoice plus these handlers and render the editable document surface.
  const patch = (values: Partial<Invoice>) => setInv((c) => ({ ...c, ...values }));
  const setItem = (id: number, key: keyof Item, value: string) =>
    patch({
      items: inv.items.map((i) =>
        i.id === id ? { ...i, [key]: key === "name" ? value : Number(value) } : i,
      ),
    });
  const addItem = () =>
    patch({ items: [...inv.items, { id: Date.now(), name: "", qty: 1, rate: 0 }] });
  const removeItem = (id: number) => patch({ items: inv.items.filter((i) => i.id !== id) });

  // Balance due is always derived — Total − Amount paid — and is never stored
  // as its own editable value. Recomputed whenever any line item, tax,
  // discount or amount paid changes. If the client overpays, the balance
  // shows as a negative "credit" amount.
  const totals = useMemo(() => computeTotals(inv), [inv]);

  // Currency & date formatting is owned entirely by the Company Profile
  // (no per-invoice override). Falls back to the app's original US-style
  // formatting when no profile has been saved.
  const prefs = useMemo(() => formatPrefsOf(profile), [profile]);
  const fmtMoney = useMemo(() => (v: number) => formatMoney(v, prefs), [prefs]);
  const fmtDate = useMemo(() => (iso: string) => formatDate(iso, prefs.dateFormat), [prefs]);
  // Payable To / banking footer — profile-owned, like the signature and the
  // currency formatters. Shown on the document (and PDF) only when filled in.
  const banking = useMemo(() => bankingDetailsOf(profile), [profile]);

  // ---- Visual layer: the swappable template ----
  // `selectedTemplate` decides which layout renders the invoice on screen and
  // which design the PDF exporter draws. No picker UI yet — change the state
  // value (React DevTools, or the default above) to swap templates live.
  const template = getInvoiceTemplate(inv.selectedTemplate);
  const Layout = template.Layout;

  // Everything a template layout needs, built once so the editing view and the
  // preview modal render from the exact same data and formatters — only the
  // `preview` flag differs. In preview the edit handlers are never invoked
  // (the document hides every editing control), so they are passed as-is.
  const layoutProps: Omit<InvoiceTemplateProps, "preview"> = {
    inv,
    totals,
    patch,
    setItem,
    addItem,
    removeItem,
    onEditProfile: () => setProfileOpen(true),
    formatMoney: fmtMoney,
    formatDate: fmtDate,
    logoUrl: profile.logo,
    // The sender's identity block, read straight from the saved Company
    // Profile. `business` / `address` fall back to the invoice's own copy so
    // invoices saved before this became profile-only still show their sender.
    businessName: profile.businessName || inv.business,
    businessAddress: profile.address || inv.address,
    businessPhone: profile.phone || inv.fromPhone || "",
    businessEmail: profile.email,
    signatureUrl: profile.signatureUrl,
    banking,
  };

  // Overlay "Save": persist the profile, keep it in state, and let it fill any
  // field the current invoice has left blank (never overwrites typed-in values
  // — see `applyCompanyProfile`).
  const handleProfileSave = (next: CompanyProfile) => {
    const prev = profile;
    saveCompanyProfile(next);
    setProfile(next);
    setProfileSaved(true);
    // Was auto-numbering already live before this save? (An unsaved profile —
    // e.g. the out-of-the-box defaults — does not count.)
    const wasActive = profileSaved && hasInvoiceNumbering(prev);
    setInv((current) => {
      let updated = applyCompanyProfile(current, next);
      // Re-issue this invoice's number under the new scheme when the user has
      // not hand-picked it AND numbering is now active because either a setting
      // changed or it was just switched on for the first time. This makes the
      // on-screen number match the dialog's "Next invoice number" preview
      // immediately. A manually customised number is left untouched. The
      // counter is not advanced here — the invoice holds the new slot until it
      // is downloaded or cleared.
      if (
        updated.invoiceNoAutoGenerated &&
        hasInvoiceNumbering(next) &&
        (invoiceNumberingChanged(prev, next) || !wasActive)
      ) {
        updated = {
          ...updated,
          invoiceNo: currentInvoiceNumber(next),
          invoiceNoCounterAdvanced: false,
        };
      }
      return updated;
    });
  };

  const handleClearInvoice = () => {
    localStorage.removeItem("rapidai-invoice");
    // Reset the per-invoice fields only, then re-apply the saved profile so a
    // fresh invoice still starts from the business identity.
    const blank: Invoice = {
      ...initial,
      selectedTemplate: inv.selectedTemplate,
      items: [{ id: Date.now(), name: "", qty: 1, rate: 0 }],
    };

    // If the invoice being discarded was auto-numbered from an active saved
    // scheme and a download has not already consumed its counter slot, consume
    // it now — so download-then-clear advances the counter exactly once, and
    // clear-without-download still advances it once.
    let nextProfile = profile;
    if (
      profileSaved &&
      inv.invoiceNoAutoGenerated &&
      !inv.invoiceNoCounterAdvanced &&
      hasInvoiceNumbering(profile)
    ) {
      nextProfile = advanceInvoiceCounter(profile);
    }

    let next = applyCompanyProfile(blank, nextProfile);
    if (hasInvoiceNumbering(nextProfile)) {
      next = {
        ...next,
        invoiceNo: currentInvoiceNumber(nextProfile),
        invoiceNoAutoGenerated: true,
        invoiceNoCounterAdvanced: false,
      };
      // Persist the scheme (and any counter advance) and mark numbering active.
      saveCompanyProfile(nextProfile);
      setProfile(nextProfile);
      setProfileSaved(true);
    } else if (nextProfile !== profile) {
      saveCompanyProfile(nextProfile);
      setProfile(nextProfile);
    }
    setInv(next);
  };

  const handleDownload = async () => {
    setDownloadError(null);
    setDownloading(true);
    try {
      const { generateInvoicePdf } = await import("@/lib/invoice-pdf");
      await generateInvoicePdf(inv, totals, prefs, profile.signatureUrl, banking, profile.logo, {
        businessName: profile.businessName || inv.business,
        businessAddress: profile.address || inv.address,
        businessPhone: profile.phone || inv.fromPhone || "",
        businessEmail: profile.email,
      });
      // The invoice has been issued as a PDF. If it carried an auto-generated
      // number from an active saved scheme whose slot has not been consumed
      // yet, advance the counter now so the next invoice gets a fresh number.
      // The downloaded invoice keeps the number printed on that PDF; only the
      // counter for future numbers moves, and only once (a later "Clear
      // invoice" sees `invoiceNoCounterAdvanced` and does not advance again).
      if (
        profileSaved &&
        inv.invoiceNoAutoGenerated &&
        !inv.invoiceNoCounterAdvanced &&
        hasInvoiceNumbering(profile)
      ) {
        const advanced = advanceInvoiceCounter(profile);
        saveCompanyProfile(advanced);
        setProfile(advanced);
        setInv((c) => ({ ...c, invoiceNoCounterAdvanced: true }));
      }
    } catch (err) {
      console.error("Invoice PDF generation failed", err);
      setDownloadError("Could not generate the PDF. Please try again.");
    } finally {
      setDownloading(false);
    }
  };

  return (
    <>
      <div className="border-b border-border bg-card print:hidden">
        <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-center gap-x-3 gap-y-1 px-4 py-3 text-xs text-muted-foreground lg:px-6">
          <span>
            Currency <span className="font-medium text-foreground">{prefs.currencyDisplay}</span>
          </span>
          <button
            type="button"
            onClick={() => setCurrencyOpen(true)}
            className="font-medium text-primary hover:underline"
          >
            Change
          </button>
        </div>
      </div>
      <div className="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-8 lg:flex-row lg:px-6">
        <Layout {...layoutProps} preview={false} />

        <aside className="w-full shrink-0 space-y-4 lg:sticky lg:top-6 lg:w-60 lg:self-start print:hidden">
          <Button size="lg" className="w-full" onClick={handleDownload} disabled={downloading}>
            {downloading ? (
              <>
                <Loader2 className="animate-spin" /> Preparing PDF…
              </>
            ) : (
              <>
                <Download /> Download Invoice
              </>
            )}
          </Button>
          <Button
            size="lg"
            variant="outline"
            className="w-full"
            onClick={() => setPreviewOpen(true)}
          >
            <Eye /> Preview
          </Button>
          {downloadError && (
            <p className="text-xs leading-5 text-destructive" role="alert">
              {downloadError}
            </p>
          )}

          <div className="space-y-2 rounded-sm border border-border bg-card p-4">
            <p className="text-xs font-medium text-muted-foreground">Template</p>
            <div className="grid gap-1.5">
              {invoiceTemplateList.map((tpl) => {
                const active = tpl.id === inv.selectedTemplate;
                return (
                  <button
                    key={tpl.id}
                    type="button"
                    aria-pressed={active}
                    onClick={() => patch({ selectedTemplate: tpl.id })}
                    className={cn(
                      "rounded-sm border px-3 py-2 text-left transition-colors",
                      active
                        ? "border-primary bg-accent text-foreground"
                        : "border-border text-muted-foreground hover:border-primary/50 hover:text-foreground",
                    )}
                  >
                    <span className="block text-sm font-medium">{tpl.name}</span>
                    <span className="mt-0.5 block text-[11px] leading-4">{tpl.description}</span>
                  </button>
                );
              })}
            </div>
          </div>

          <div className="space-y-2 rounded-sm border border-border bg-card p-4">
            <Button variant="ghost" size="sm" className="w-full" onClick={handleClearInvoice}>
              Clear invoice
            </Button>
          </div>
          <p className="text-xs leading-5 text-muted-foreground">
            No signup. Your details are saved only in this browser.
          </p>
        </aside>
      </div>

      <CompanyProfileDialog
        open={profileOpen}
        onOpenChange={setProfileOpen}
        profile={profile}
        onSave={handleProfileSave}
      />

      <CurrencySettingsDialog
        open={currencyOpen}
        onOpenChange={setCurrencyOpen}
        profile={profile}
        onSave={handleProfileSave}
      />

      <InvoicePreviewDialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <Layout {...layoutProps} preview />
      </InvoicePreviewDialog>
    </>
  );
}
